-- MySQL Script generated by MySQL Workbench
-- Fri May 20 10:26:32 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SOFKA_PLAY
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SOFKA_PLAY
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SOFKA_PLAY` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `SOFKA_PLAY` ;

--
-- Table structure for table `Rondas`
--

DROP TABLE IF EXISTS `Rondas`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `Rondas` (
  `idRonda` int NOT NULL,
  `premio` decimal(10,2) NOT NULL,
  PRIMARY KEY (`idRonda`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8_spanish_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `Rondas`
--

LOCK TABLES `Rondas` WRITE;
/*!40000 ALTER TABLE `Rondas` DISABLE KEYS */;
INSERT INTO `Rondas` VALUES (1,100000.00),(2,250000.00),(3,400000.00),(4,600000.00),(5,100000.00);
/*!40000 ALTER TABLE `Rondas` ENABLE KEYS */;
UNLOCK TABLES;



-- -----------------------------------------------------
-- Table `SOFKA_PLAY`.`Categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Categorias`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `Categorias` (
  `idCategoria` int NOT NULL,
  `nivel` int NOT NULL,
  `idRonda` int NOT NULL,
  PRIMARY KEY (`idCategoria`),
  KEY `fk_Categorias_Rondas_idx` (`idRonda`),
  CONSTRAINT `fk_Categorias_Rondas` FOREIGN KEY (`idRonda`) REFERENCES `Rondas` (`idRonda`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8_spanish_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `Categorias`
--

LOCK TABLES `Categorias` WRITE;
/*!40000 ALTER TABLE `Categorias` DISABLE KEYS */;
INSERT INTO `Categorias` VALUES (2005221019,1,1),(2005221020,2,2),(2005221021,3,3),(2005221022,4,4),(2005221023,5,5);
/*!40000 ALTER TABLE `Categorias` ENABLE KEYS */;
UNLOCK TABLES;


-- -----------------------------------------------------
-- Table `SOFKA_PLAY`.`Preguntas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SOFKA_PLAY`.`Preguntas` (
  `idPregunta` INT NOT NULL AUTO_INCREMENT,
  `pregunta` VARCHAR(200) NOT NULL,
  `idCategoria` INT NOT NULL,
  PRIMARY KEY (`idPregunta`),
  INDEX `fk_Preguntas_Categorias1_idx` (`idCategoria` ASC) VISIBLE,
  CONSTRAINT `fk_Preguntas_Categorias1`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `SOFKA_PLAY`.`Categorias` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SOFKA_PLAY`.`Opciones_Respuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SOFKA_PLAY`.`Opciones_Respuesta` (
  `idOpciones_Respuesta` INT NOT NULL AUTO_INCREMENT,
  `respuesta` VARCHAR(200) NOT NULL,
  `correcta` BIT(1) NOT NULL,
  `idPregunta` INT NOT NULL,
  PRIMARY KEY (`idOpciones_Respuesta`),
  INDEX `fk_Opciones_Respuesta_Preguntas1_idx` (`idPregunta` ASC) VISIBLE,
  CONSTRAINT `fk_Opciones_Respuesta_Preguntas1`
    FOREIGN KEY (`idPregunta`)
    REFERENCES `SOFKA_PLAY`.`Preguntas` (`idPregunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SOFKA_PLAY`.`Jugadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SOFKA_PLAY`.`Jugadores` (
  `idJugadore` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `saldoTotal` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idJugadore`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SOFKA_PLAY`.`Jugadores_Rondas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SOFKA_PLAY`.`Jugadores_Rondas` (
  `idRonda` INT NOT NULL,
  `idJugadore` INT NOT NULL,
  `fecha` DATETIME NOT NULL,
  PRIMARY KEY (`idRonda`, `idJugadore`),
  INDEX `fk_Rondas_has_Jugadores_Jugadores1_idx` (`idJugadore` ASC) VISIBLE,
  INDEX `fk_Rondas_has_Jugadores_Rondas1_idx` (`idRonda` ASC) VISIBLE,
  CONSTRAINT `fk_Rondas_has_Jugadores_Rondas1`
    FOREIGN KEY (`idRonda`)
    REFERENCES `SOFKA_PLAY`.`Rondas` (`idRonda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rondas_has_Jugadores_Jugadores1`
    FOREIGN KEY (`idJugadore`)
    REFERENCES `SOFKA_PLAY`.`Jugadores` (`idJugadore`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
